version: 0.2

env:
  secrets-manager:
    SONAR_TOKEN: "/project/sonar/token:SONAR_TOKEN"
  variables:
    SONAR_PROJECT_KEY: "node-demo-app"
    SONAR_HOST_URL: "http://13.233.63.80:9000"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "📦 Installing unzip, wget, Java (needed for SonarScanner)..."
      - apt-get update -y
      - apt-get install -y unzip wget default-jre
      - echo "⬇️ Downloading SonarScanner CLI..."
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip -q sonar-scanner-cli-5.0.1.3006-linux.zip

  pre_build:
    commands:
      - echo "✅ Adding SonarScanner to PATH..."
      - export PATH=$PATH:$(pwd)/sonar-scanner-5.0.1.3006-linux/bin
      - sonar-scanner --version
      - echo "✅ Preparing for SonarQube scan..."
      - ls -la

  build:
    commands:
      - echo "🧪 Running tests and generating coverage..."
      - npm install
      - npm test -- --coverage
      - echo "📄 Checking for coverage report..."
      - ls -la coverage || echo "⚠️ Coverage folder missing!"
      - echo "🚀 Running SonarQube analysis..."
      - |
        sonar-scanner \
          -Dsonar.projectKey=$SONAR_PROJECT_KEY \
          -Dsonar.sources=. \
          -Dsonar.tests=tests \
          -Dsonar.test.inclusions=tests/**/*.test.js \
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN

artifacts:
  files:
    - '**/*'
  discard-paths: yes
